### ISSUE TITLE
Gitlab CI integration

### ISSUE THREAD

**Issue by bentiss** [libratbag/ratbag-emu#28]
[just taking notes, I won't have time to work on this today]

Currently few problems:
- we can not create a status from github action anymore (`Resource not accessible by integration`)
- gitlab CI jobs can not update the new status anymore. The API says everything went fine but the UI doesn't show it anymore

# next solution:

use polling with gitlab CI API:
- https://docs.gitlab.com/ee/api/pipelines.html and 
- https://docs.gitlab.com/ee/api/jobs.html#get-a-log-file

Ideally, we should create a job in the workload per gitlab job, so we can individually monitor them. Also, the gitlab API allows to retrieve the logs of a job, so it would be interesting to pull this here too so we do not have multiple clicks to follow.

The first job would create the pipeline, retrieve the URL in the answer and can forward this information to the subjobs with an artifact (https://help.github.com/en/actions/configuring-and-managing-workflows/persisting-workflow-data-using-artifacts)

Next question: can we create a job in a workload from within the workload? This would allow to first trigger the pipeline, get its description and create the monitoring jobs accordingly

# other discarded solutions:
- checks API
  - seems that we need a github app for that
- gitlab native github integration
  - we need a premium or silver subscription, which we don't have in freedesktop

**Comment by FFY00** [comment]
> Currently few problems:
> 
>     * we can not create a status from github action anymore (`Resource not accessible by integration`)
> 
>     * gitlab CI jobs can not update the new status anymore. The API says everything went fine but the UI doesn't show it anymore

What do you mean? This is working.

https://github.com/FFY00/ratbag-emu/commits/codecov

**Comment by bentiss** [comment]
> What do you mean? This is working.
> 
> https://github.com/FFY00/ratbag-emu/commits/codecov

Huh. It was not appearing on the PR, so maybe that's just a PR problem, or just a local glitch

**Comment by FFY00** [comment]
Because it was broken, you fixed it in https://gitlab.freedesktop.org/bentiss/libratbag-tests/commit/d61bd619e12c00ebc6098afa3195d76e24af4b5e.

**Comment by bentiss** [comment]
Seems like it sort of work, yes. I am still not that happy not seeing directly the results in the PR directly, but this will do
