### ISSUE TITLE
Use UHIDDevice capabilities to access the device nodes

### ISSUE THREAD

**Issue by bentiss** [libratbag/ratbag-emu#41]
Currently, the `catch_evdev_events()` function relies on a manual discovery of `pyudev` to check which device node belongs to which. However, `UHIDDevice` already has callbacks in place to get notified when the kernel adds a new children device (being evdev, led or power supply for instance).

We better have the list of evdev nodes fetched from that information so we ensure the evdev nodes associated with a given endpoint are correct.

**Comment by FFY00** [comment]
Yes, that is the intent of #39.
